name: CalVar

on:
  workflow_dispatch:
    inputs:
      game_symbol:
        description: "Game symbol"
        required: true
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        depths: [64]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential pgn-extract clang-tools pychess
        pip3 install python-chess
        
    - name: Build project
      run: |
        test -f bin/build.sh || (echo "File build.sh not found" && exit 1)
        chmod +x bin/build.sh
        bin/build.sh || echo "Compilation error"
        
    - name: Verify binary exists
      run: test -f baeagn || (echo "Binary not found" && exit 1)
      
    - name: Install binary
      run: sudo install -m 0755 baeagn /usr/local/bin
      
    - name: Check for benchmark script
      run: test -f bin/bench.sh || (echo "Benchmark script not found" && exit 1)

    - name: Save PGN to file
      run: |
        mkdir -p input
        cp -a pgn/${{ inputs.game_symbol }}.pgn input/game.pgn

    - name: Run benchmarks ${{ inputs.game_symbol }}
      run: |
        bin/bench.sh ${{ matrix.depths }} ${{ inputs.game_symbol }}
        
    - name: Upload analysis files
      uses: actions/upload-artifact@v4
      with:
        name: analysis-${{ inputs.game_symbol }}-${{ matrix.depths }} 
        path: ${{ inputs.game_symbol }}.d${{ matrix.depths }}.anl
      
